version: '3.8'

services:
  backend:
    image: ghcr.io/bigsk1/yt-webui-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./docker/Downloads:/root/Downloads
    restart: unless-stopped

  frontend:
    image: ghcr.io/bigsk1/yt-webui-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./docker/Downloads:/usr/share/nginx/html/downloads
    restart: unless-stopped

volumes:
  downloads: