version: '3.8'

services:
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./docker/Downloads:/root/Downloads
    restart: unless-stopped

  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./docker/Downloads:/usr/share/nginx/html/downloads
    restart: unless-stopped

volumes:
  downloads: